[project]
name = "shop-titans-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.4",
    "pillow>=11.2.1",
    "pyscreeze>=1.0.1",
    "scikit-learn>=1.6.1",
]
